name: Build and Release KMP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew assemble
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Build iOS Framework
        run: ./gradlew :shared:assembleXCFramework
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Compress XCFramework
        run: |
          cd ./shared/build/XCFrameworks/release
          zip -r shared.xcframework.zip shared.xcframework

      - name: Compute checksum
        id: checksum
        run: |
          swift package compute-checksum ./shared/build/XCFrameworks/release/shared.xcframework.zip > checksum.txt
          CHECKSUM=$(cat checksum.txt)
          echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Upload artifact and capture log
        id: upload_log
        run: |
          output=$(mktemp)
          actions/upload-artifact@v4 \
            --name shared.xcframework \
            --path ./shared/build/XCFrameworks/release/shared.xcframework.zip \
            > $output
          ARTIFACT_URL=$(grep -oP 'Artifact download URL: \K.*' $output)
          echo "artifact-url=$ARTIFACT_URL" >> $GITHUB_OUTPUT

      - name: Get Artifact URL and Checksum
        run: |
          ARTIFACT_URL=${{ steps.upload_log.outputs.artifact-url }}
          echo "Artifact URL: $ARTIFACT_URL"
          echo "Checksum: ${{ steps.checksum.outputs.checksum }}"